import {
  Baby,
  Banknote,
  Bike,
  Book,
  Briefcase,
  Bus,
  Camera,
  Car,
  Clapperboard,
  Coffee,
  CreditCard,
  Dumbbell,
  Ellipsis,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  Headphones,
  HeartPulse,
  Home,
  Landmark,
  Lightbulb,
  Music,
  Paintbrush,
  PawPrint,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Receipt,
  Repeat,
  Salad,
  School,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  Stethoscope,
  TrainFront,
  TrendingUp,
  Tv,
  User,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const ICON_SET: { name: string; icon: LucideIcon }[] = [
  { name: "Home", icon: Home },
  { name: "Utensils", icon: Utensils },
  { name: "ShoppingBasket", icon: ShoppingBasket },
  { name: "Car", icon: Car },
  { name: "ShoppingBag", icon: ShoppingBag },
  { name: "Clapperboard", icon: Clapperboard },
  { name: "HeartPulse", icon: HeartPulse },
  { name: "Plane", icon: Plane },
  { name: "GraduationCap", icon: GraduationCap },
  { name: "Receipt", icon: Receipt },
  { name: "Repeat", icon: Repeat },
  { name: "User", icon: User },
  { name: "Coffee", icon: Coffee },
  { name: "Zap", icon: Zap },
  { name: "Wifi", icon: Wifi },
  { name: "Dumbbell", icon: Dumbbell },
  { name: "Paintbrush", icon: Paintbrush },
  { name: "Book", icon: Book },
  { name: "Music", icon: Music },
  { name: "Gift", icon: Gift },
  { name: "PawPrint", icon: PawPrint },
  { name: "Baby", icon: Baby },
  { name: "Scissors", icon: Scissors },
  { name: "Wrench", icon: Wrench },
  { name: "Phone", icon: Phone },
  { name: "CreditCard", icon: CreditCard },
  { name: "Banknote", icon: Banknote },
  { name: "PiggyBank", icon: PiggyBank },
  { name: "TrendingUp", icon: TrendingUp },
  { name: "Wallet", icon: Wallet },
  { name: "Landmark", icon: Landmark },
  { name: "Briefcase", icon: Briefcase },
  { name: "Film", icon: Film },
  { name: "Gamepad2", icon: Gamepad2 },
  { name: "Shirt", icon: Shirt },
  { name: "Pizza", icon: Pizza },
  { name: "Salad", icon: Salad },
  { name: "Bus", icon: Bus },
  { name: "TrainFront", icon: TrainFront },
  { name: "Bike", icon: Bike },
  { name: "Fuel", icon: Fuel },
  { name: "Stethoscope", icon: Stethoscope },
  { name: "Pill", icon: Pill },
  { name: "School", icon: School },
  { name: "Globe", icon: Globe },
  { name: "Camera", icon: Camera },
  { name: "Headphones", icon: Headphones },
  { name: "Tv", icon: Tv },
  { name: "Lightbulb", icon: Lightbulb },
  { name: "Ellipsis", icon: Ellipsis },
];

const ICON_MAP = new Map(ICON_SET.map((e) => [e.name, e.icon]));

export function iconByName(name: string | undefined | null): LucideIcon {
  return ICON_MAP.get(name ?? "") ?? Ellipsis;
}

export interface DefaultCategoryDef {
  name: string;
  icon: string;
  isSystem: boolean;
}

export const DEFAULT_CATEGORIES: DefaultCategoryDef[] = [
  { name: "Housing", icon: "Home", isSystem: true },
  { name: "Food", icon: "Utensils", isSystem: true },
  { name: "Groceries", icon: "ShoppingBasket", isSystem: true },
  { name: "Transport", icon: "Car", isSystem: true },
  { name: "Shopping", icon: "ShoppingBag", isSystem: true },
  { name: "Entertainment", icon: "Clapperboard", isSystem: true },
  { name: "Health", icon: "HeartPulse", isSystem: true },
  { name: "Travel", icon: "Plane", isSystem: true },
  { name: "Education", icon: "GraduationCap", isSystem: true },
  { name: "Bills", icon: "Receipt", isSystem: true },
  { name: "Subscriptions", icon: "Repeat", isSystem: true },
  { name: "Personal", icon: "User", isSystem: true },
  { name: "Other", icon: "Ellipsis", isSystem: true },
];
